### ISSUE TITLE
Set the TTL to the minimum (300)

### ISSUE THREAD

**Issue by FredericHardy** [EmixamPP/synology-ddns-gandi#1]
Just a suggestion:
As the IP is dynamic it should have the lower TTL possible, so
$data = '{"rrset_values": ["' . $ipv4 . '"],"rrset_ttl":300}';
instead of
$data = '{"rrset_values": ["' . $ipv4 . '"]}';
Thanks!

**Comment by EmixamPP** [comment]
The drawback is that every client will perform a slower request after every 300sec.
For instance, my IP is dynamic but rarely changes. And if it does, the negative TTL will do the job.

Instead, we could first perform a GET request to obtain the TTL of the record (if exists).
And then perform the PUT using the current TTL.
Like that, anyone can choose which TTL he wants, by using the Gandi web interface the first time.

**Comment by FredericHardy** [comment]
Yes your solution is better, thanks!

**Comment by EmixamPP** [comment]
I reopen the issue as a reminder, because I forgot to do it
