### ISSUE TITLE
Getting failure everytime I'm trying to add it

### ISSUE THREAD

**Issue by MayContainVennom** [EmixamPP/synology-ddns-gandi#3]
Hello

I am trying to add this and every time I'm getting a failure. Could this be due to the move to PAT over the deprecated API keys?

I have given the key all the Domain permissions yet it still fails.
<img width="452" alt="image" src="https://github.com/EmixamPP/synology-ddns-gandi/assets/5930954/b31520d0-7f84-4ac6-aa4e-2d160a64a263">

![image](https://github.com/EmixamPP/synology-ddns-gandi/assets/5930954/0c22e278-e85b-4270-97d0-a46ad27c3e3d)

![image](https://github.com/EmixamPP/synology-ddns-gandi/assets/5930954/a5bc0be0-5d90-4c01-a46f-1265a6745277)

**Comment by EmixamPP** [comment]
Hum, unfortunately, Gandi is no longer my registrar. So it's impossible for me to investigate this problem.
Nevertheless, I can accept any PR, or even give collaborator access to the repo.

**Comment by Pinpin31** [comment]
Hi
this PR #4 should fix the problem.
